name: Deploy to Production

on:
  workflow_run:
    workflows: ["Docker Publish"]
    types:
      - completed
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    if: ${{ github.event.workflow_run.conclusion == 'success' }}

    steps:
      - name: Set up SSH key
        uses: appleboy/ssh-action@v0.1.5
        with:
          host: ${{ secrets.SSH_HOST }}
          username: ${{ secrets.SSH_USERNAME }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          port: 22
          script: |
            cd ${{ secrets.SSH_PATH }}
            echo ${{ secrets.GH_TOKEN }} | docker login ghcr.io -u ${{ github.actor }} --password-stdin
            docker image prune -f
            docker-compose pull ${GITHUB_REPOSITORY##*/}
            docker-compose up -d ${GITHUB_REPOSITORY##*/}
            docker logout ghcr.io